using Microsoft.EntityFrameworkCore;
using WideWorldImportersBI.Entities.Oltp;

namespace WideWorldImportersBI.Data.Oltp;

/// <summary>
/// Entity Framework DbContext for the WideWorldImporters OLTP database
/// This context maps to the real WideWorldImporters database tables
/// Used for transactional operations and real-time data access
/// </summary>
public class OltpDbContext : DbContext
{
    public OltpDbContext(DbContextOptions<OltpDbContext> options) : base(options)
    {
    }

    // WideWorldImporters Sales Schema
    public DbSet<Customer> Customers { get; set; } = null!;
    public DbSet<Order> Orders { get; set; } = null!;
    public DbSet<Invoice> Invoices { get; set; } = null!;
    public DbSet<InvoiceLine> InvoiceLines { get; set; } = null!;

    // WideWorldImporters Warehouse Schema
    public DbSet<Product> Products { get; set; } = null!;

    // BI Platform Authentication (Custom tables)
    public DbSet<User> Users { get; set; } = null!;
    public DbSet<Role> Roles { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure Customer entity
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customers", "Sales");
            entity.HasKey(e => e.CustomerId);
            
            // ValidFrom and ValidTo are GENERATED ALWAYS columns (temporal table)
            // Must use Metadata to tell EF these are ALWAYS generated by database
            entity.Property(e => e.ValidFrom)
                  .ValueGeneratedOnAddOrUpdate()
                  .Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
            entity.Property(e => e.ValidTo)
                  .ValueGeneratedOnAddOrUpdate()
                  .Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
            
            entity.HasMany(c => c.Orders)
                  .WithOne(o => o.Customer)
                  .HasForeignKey(o => o.CustomerId)
                  .OnDelete(DeleteBehavior.Restrict);

            entity.HasMany(c => c.Invoices)
                  .WithOne(i => i.Customer)
                  .HasForeignKey(i => i.CustomerId)
                  .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure Product entity
        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("StockItems", "Warehouse");
            entity.HasKey(e => e.StockItemId);
            
            // Mark computed columns - EF should not insert/update values into these
            entity.Property(e => e.SearchDetails).ValueGeneratedOnAddOrUpdate();
            entity.Property(e => e.Tags).ValueGeneratedOnAddOrUpdate();
            
            // ValidFrom and ValidTo are GENERATED ALWAYS columns
            entity.Property(e => e.ValidFrom).ValueGeneratedOnAddOrUpdate();
            entity.Property(e => e.ValidTo).ValueGeneratedOnAddOrUpdate();
            
            entity.HasMany(p => p.InvoiceLines)
                  .WithOne(il => il.StockItem)
                  .HasForeignKey(il => il.StockItemId)
                  .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure Order entity
        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Orders", "Sales");
            entity.HasKey(e => e.OrderId);
        });

        // Configure Invoice entity
        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.ToTable("Invoices", "Sales");
            entity.HasKey(e => e.InvoiceId);
            
            // Computed columns - managed by SQL Server
            entity.Property(e => e.ConfirmedDeliveryTime).ValueGeneratedOnAddOrUpdate();
            entity.Property(e => e.ConfirmedReceivedBy).ValueGeneratedOnAddOrUpdate();
            entity.Property(e => e.ReturnedDeliveryData).ValueGeneratedOnAddOrUpdate();
            
            entity.HasMany(i => i.InvoiceLines)
                  .WithOne(il => il.Invoice)
                  .HasForeignKey(il => il.InvoiceId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // Configure InvoiceLine entity
        modelBuilder.Entity<InvoiceLine>(entity =>
        {
            entity.ToTable("InvoiceLines", "Sales");
            entity.HasKey(e => e.InvoiceLineId);
        });

        // Configure User entity (Custom BI Platform table)
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("BiUsers", "Application");
            entity.HasKey(e => e.UserId);
            
            entity.HasIndex(e => e.Username).IsUnique();
            entity.HasIndex(e => e.Email).IsUnique();

            entity.HasOne(u => u.Role)
                  .WithMany(r => r.Users)
                  .HasForeignKey(u => u.RoleId)
                  .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure Role entity (Custom BI Platform table)
        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("BiRoles", "Application");
            entity.HasKey(e => e.RoleId);
            
            entity.HasIndex(e => e.RoleName).IsUnique();
        });

        // Seed default roles
        modelBuilder.Entity<Role>().HasData(
            new Role { RoleId = 1, RoleName = "Admin", Description = "Administrator with full access", CreatedAt = DateTime.UtcNow },
            new Role { RoleId = 2, RoleName = "User", Description = "Standard user with read access", CreatedAt = DateTime.UtcNow }
        );

        // Seed default admin user (Password: Admin@123)
        modelBuilder.Entity<User>().HasData(
            new User
            {
                UserId = 1,
                Username = "admin",
                Email = "admin@wideworldimporters.com",
                PasswordHash = "$2a$11$rBLRG5K7GDlpGYGg8YJYa.KMG7X3TGjGC2l5QKGM2VE8jK9UhG9Hy", // Admin@123
                FirstName = "System",
                LastName = "Administrator",
                IsActive = true,
                RoleId = 1,
                CreatedAt = DateTime.UtcNow
            }
        );
    }
}
