// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WideWorldImportersBI.Data.Oltp;

#nullable disable

namespace WideWorldImportersBI.Data.Oltp.Migrations
{
    [DbContext(typeof(OltpDbContext))]
    [Migration("20260201195210_CreateBiUsersTables")]
    partial class CreateBiUsersTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("AccountOpenedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AccountOpenedDate");

                    b.Property<int?>("AlternateContactPersonId")
                        .HasColumnType("int")
                        .HasColumnName("AlternateContactPersonID");

                    b.Property<int>("BillToCustomerId")
                        .HasColumnType("int")
                        .HasColumnName("BillToCustomerID");

                    b.Property<int?>("BuyingGroupId")
                        .HasColumnType("int")
                        .HasColumnName("BuyingGroupID");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CreditLimit");

                    b.Property<int>("CustomerCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerCategoryID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CustomerName");

                    b.Property<string>("DeliveryAddressLine1")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DeliveryAddressLine1");

                    b.Property<string>("DeliveryAddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DeliveryAddressLine2");

                    b.Property<int>("DeliveryCityId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryCityID");

                    b.Property<int>("DeliveryMethodId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryMethodID");

                    b.Property<string>("DeliveryPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DeliveryPostalCode");

                    b.Property<string>("DeliveryRun")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("DeliveryRun");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FaxNumber");

                    b.Property<bool>("IsOnCreditHold")
                        .HasColumnType("bit")
                        .HasColumnName("IsOnCreditHold");

                    b.Property<bool>("IsStatementSent")
                        .HasColumnType("bit")
                        .HasColumnName("IsStatementSent");

                    b.Property<int>("LastEditedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastEditedBy");

                    b.Property<int>("PaymentDays")
                        .HasColumnType("int")
                        .HasColumnName("PaymentDays");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("PostalAddressLine1")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("PostalAddressLine1");

                    b.Property<string>("PostalAddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("PostalAddressLine2");

                    b.Property<int>("PostalCityId")
                        .HasColumnType("int")
                        .HasColumnName("PostalCityID");

                    b.Property<string>("PostalPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalPostalCode");

                    b.Property<int>("PrimaryContactPersonId")
                        .HasColumnType("int")
                        .HasColumnName("PrimaryContactPersonID");

                    b.Property<string>("RunPosition")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("RunPosition");

                    b.Property<decimal>("StandardDiscountPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("StandardDiscountPercentage");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("WebsiteURL");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", "Sales");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("AccountsPersonId")
                        .HasColumnType("int")
                        .HasColumnName("AccountsPersonID");

                    b.Property<int>("BillToCustomerId")
                        .HasColumnType("int")
                        .HasColumnName("BillToCustomerID");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comments");

                    b.Property<DateTime?>("ConfirmedDeliveryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConfirmedDeliveryTime");

                    b.Property<string>("ConfirmedReceivedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConfirmedReceivedBy");

                    b.Property<int>("ContactPersonId")
                        .HasColumnType("int")
                        .HasColumnName("ContactPersonID");

                    b.Property<string>("CreditNoteReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreditNoteReason");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerPurchaseOrderNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CustomerPurchaseOrderNumber");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliveryInstructions");

                    b.Property<int>("DeliveryMethodId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryMethodID");

                    b.Property<string>("DeliveryRun")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("DeliveryRun");

                    b.Property<string>("InternalComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InternalComments");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InvoiceDate");

                    b.Property<bool>("IsCreditNote")
                        .HasColumnType("bit")
                        .HasColumnName("IsCreditNote");

                    b.Property<int>("LastEditedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastEditedBy");

                    b.Property<DateTime>("LastEditedWhen")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastEditedWhen");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("PackedByPersonId")
                        .HasColumnType("int")
                        .HasColumnName("PackedByPersonID");

                    b.Property<string>("ReturnedDeliveryData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReturnedDeliveryData");

                    b.Property<string>("RunPosition")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("RunPosition");

                    b.Property<int>("SalespersonPersonId")
                        .HasColumnType("int")
                        .HasColumnName("SalespersonPersonID");

                    b.Property<int>("TotalChillerItems")
                        .HasColumnType("int")
                        .HasColumnName("TotalChillerItems");

                    b.Property<int>("TotalDryItems")
                        .HasColumnType("int")
                        .HasColumnName("TotalDryItems");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices", "Sales");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceLineId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.Property<decimal>("ExtendedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExtendedPrice");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    b.Property<int>("LastEditedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastEditedBy");

                    b.Property<DateTime>("LastEditedWhen")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastEditedWhen");

                    b.Property<decimal>("LineProfit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LineProfit");

                    b.Property<int>("PackageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PackageTypeID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("StockItemId")
                        .HasColumnType("int")
                        .HasColumnName("StockItemID");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxRate");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("StockItemId");

                    b.ToTable("InvoiceLines", "Sales");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("BackorderOrderId")
                        .HasColumnType("int")
                        .HasColumnName("BackorderOrderID");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comments");

                    b.Property<int>("ContactPersonId")
                        .HasColumnType("int")
                        .HasColumnName("ContactPersonID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerPurchaseOrderNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CustomerPurchaseOrderNumber");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliveryInstructions");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpectedDeliveryDate");

                    b.Property<string>("InternalComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InternalComments");

                    b.Property<bool>("IsUndersupplyBackordered")
                        .HasColumnType("bit")
                        .HasColumnName("IsUndersupplyBackordered");

                    b.Property<int>("LastEditedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastEditedBy");

                    b.Property<DateTime>("LastEditedWhen")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastEditedWhen");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<int?>("PickedByPersonId")
                        .HasColumnType("int")
                        .HasColumnName("PickedByPersonID");

                    b.Property<DateTime?>("PickingCompletedWhen")
                        .HasColumnType("datetime2")
                        .HasColumnName("PickingCompletedWhen");

                    b.Property<int>("SalespersonPersonId")
                        .HasColumnType("int")
                        .HasColumnName("SalespersonPersonID");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", "Sales");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Product", b =>
                {
                    b.Property<int>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockItemId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Brand");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    b.Property<string>("CustomFields")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CustomFields");

                    b.Property<string>("InternalComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InternalComments");

                    b.Property<bool>("IsChillerStock")
                        .HasColumnType("bit")
                        .HasColumnName("IsChillerStock");

                    b.Property<int>("LastEditedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastEditedBy");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("LeadTimeDays");

                    b.Property<string>("MarketingComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MarketingComments");

                    b.Property<int>("OuterPackageId")
                        .HasColumnType("int")
                        .HasColumnName("OuterPackageID");

                    b.Property<int>("QuantityPerOuter")
                        .HasColumnType("int")
                        .HasColumnName("QuantityPerOuter");

                    b.Property<decimal?>("RecommendedRetailPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RecommendedRetailPrice");

                    b.Property<string>("SearchDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SearchDetails");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Size");

                    b.Property<string>("StockItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StockItemName");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxRate");

                    b.Property<decimal>("TypicalWeightPerUnit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TypicalWeightPerUnit");

                    b.Property<int>("UnitPackageId")
                        .HasColumnType("int")
                        .HasColumnName("UnitPackageID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("StockItemId");

                    b.ToTable("StockItems", "Warehouse");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("BiRoles", "Application");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 52, 8, 172, DateTimeKind.Utc).AddTicks(4749),
                            Description = "Administrator with full access",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 52, 8, 172, DateTimeKind.Utc).AddTicks(4750),
                            Description = "Standard user with read access",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("BiUsers", "Application");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 52, 8, 172, DateTimeKind.Utc).AddTicks(4898),
                            Email = "admin@wideworldimporters.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$rBLRG5K7GDlpGYGg8YJYa.KMG7X3TGjGC2l5QKGM2VE8jK9UhG9Hy",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Invoice", b =>
                {
                    b.HasOne("WideWorldImportersBI.Entities.Oltp.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.InvoiceLine", b =>
                {
                    b.HasOne("WideWorldImportersBI.Entities.Oltp.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WideWorldImportersBI.Entities.Oltp.Product", "StockItem")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Order", b =>
                {
                    b.HasOne("WideWorldImportersBI.Entities.Oltp.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.User", b =>
                {
                    b.HasOne("WideWorldImportersBI.Entities.Oltp.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Invoice", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Product", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("WideWorldImportersBI.Entities.Oltp.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
